import React, { useEffect, useState } from 'react'
import { BookOpen, CalendarDays, MapPin, Plus, Send, Trash2 } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { LOCAL_AUTHOR_EXHIBITORS } from '../../data/localAuthorScenarios'

const EVENT_START = '2026-09-04'; const EVENT_END = '2026-09-13'
const newPresence = () => ({ presence_date: '', start_time: '', end_time: '', exhibitor_id: '', stand_code: '', notes: '', guaranteed: true })
const newBook = () => ({ title: '', publisher: '', cover_url: '', synopsis: '', genre: '', tags: '', featured: false, autograph_available: false, available_for_sale: false, exhibitor_id: '', stand_code: '' })
const newAutograph = () => ({ event_date: '', start_time: '', end_time: '', exhibitor_id: '', books: '', notes: '' })
const labels = { presence: 'Presença na Bienal', book: 'Livro', autograph: 'Sessão de autógrafos' }
const statuses = { draft: 'Rascunho', pending: 'Em revisão', approved: 'Aprovada', rejected: 'Precisa de ajuste' }
const Input = ({ label, value, onChange, type = 'text', required = false, ...props }) => <label className="block text-xs font-bold">{label}{required ? ' *' : ''}<input type={type} required={required} value={value} onChange={e => onChange(e.target.value)} className="auth-input mt-1 w-full rounded-xl border p-3 text-sm" {...props}/></label>
const SelectStand = ({ exhibitors, item, setItem }) => <label className="block text-xs font-bold">Estande de venda<select value={item.exhibitor_id} onChange={e => { const stand = exhibitors.find(x => x.id === e.target.value); setItem({ ...item, exhibitor_id: e.target.value, stand_code: stand?.stand_code || '' }) }} className="auth-input mt-1 w-full rounded-xl border p-3 text-sm"><option value="">Selecione…</option>{exhibitors.map(x => <option key={x.id} value={x.id}>{x.stand_code} — {x.name}</option>)}</select></label>

export default function AuthorContentRequests({ authorId, notice, agendaOnly = false, localScenario = null }) {
  const [exhibitors, setExhibitors] = useState([]); const [requests, setRequests] = useState([])
  const [kind, setKind] = useState('presence'); const [presence, setPresence] = useState(newPresence()); const [bookItems, setBookItems] = useState([newBook()]); const [autograph, setAutograph] = useState(newAutograph()); const [saving, setSaving] = useState(false)
  const activeKind = agendaOnly && kind === 'book' ? 'presence' : kind
  const load = async () => {
    if (localScenario) { setExhibitors(LOCAL_AUTHOR_EXHIBITORS); setRequests(localScenario.existingRequests || []); return }
    const [stands, history] = await Promise.all([supabase.from('exhibitors').select('id,name,stand_code').eq('active', true).is('deleted_at', null).order('stand_code'), supabase.from('author_change_requests').select('id,request_type,payload,status,created_at').eq('author_id', authorId).in('request_type', ['presence', 'book', 'autograph']).order('created_at', { ascending: false })])
    setExhibitors(stands.data || []); setRequests(history.data || [])
  }
  useEffect(() => { void load() }, [authorId, localScenario])
  const submitOne = async (requestType, payload) => {
    if (localScenario) { setRequests(current => [{ id: `local-${Date.now()}-${Math.random()}`, request_type: requestType, payload, status: 'pending' }, ...current]); return null }
    return supabase.rpc('submit_author_content_request', { p_request_type: requestType, p_payload: payload })
  }
  const submit = async e => {
    e.preventDefault(); setSaving(true)
    const payloads = activeKind === 'presence' ? [presence] : activeKind === 'autograph' ? [{ ...autograph, books: autograph.books.split(',').map(x => x.trim()).filter(Boolean) }] : bookItems.filter(book => book.title.trim()).map(book => ({ ...book, notes: book.synopsis, tags: [book.genre, ...book.tags.split(',')].map(x => x.trim()).filter(Boolean) }))
    if (!payloads.length) { setSaving(false); return notice('Adicione pelo menos um livro com título.') }
    const results = await Promise.all(payloads.map(payload => submitOne(activeKind, payload)))
    const error = results.find(result => result?.error)?.error
    setSaving(false); if (error) return notice(error.message)
    notice(localScenario ? 'Simulação: informações enviadas para revisão local.' : `${payloads.length} registro(s) enviado(s) para aprovação.`)
    if (activeKind === 'presence') setPresence(newPresence()); if (activeKind === 'autograph') setAutograph(newAutograph()); if (activeKind === 'book') setBookItems([newBook()]); void load()
  }
  const options = agendaOnly ? [['presence', 'Presença', MapPin], ['autograph', 'Autógrafo', CalendarDays]] : [['presence', 'Presença', MapPin], ['book', 'Livros', BookOpen], ['autograph', 'Autógrafo', CalendarDays]]
  return <section className="auth-card mt-5 rounded-3xl border p-5"><h2 className="text-lg font-black">{agendaOnly ? 'Minha agenda na Bienal' : 'Presença, livros e agenda'}</h2><p className="mt-1 text-xs opacity-70">Tudo é enviado para revisão antes de aparecer no Mapa e no Passaporte.</p><div className={`mt-4 grid gap-2 ${agendaOnly ? 'sm:grid-cols-2' : 'sm:grid-cols-3'}`}>{options.map(([id, label, Icon]) => <button type="button" key={id} onClick={() => setKind(id)} className={`flex items-center justify-center gap-2 rounded-xl border px-3 py-2 text-xs font-black ${activeKind === id ? 'bg-[#d43276] text-white' : 'auth-input'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div><form className="mt-4 grid gap-3" onSubmit={submit}>
    {activeKind === 'presence' && <><Input label="Data" type="date" required min={EVENT_START} max={EVENT_END} value={presence.presence_date} onChange={v => setPresence({ ...presence, presence_date: v })}/><div className="grid gap-3 sm:grid-cols-2"><Input label="Horário inicial" type="time" required value={presence.start_time} onChange={v => setPresence({ ...presence, start_time: v })}/><Input label="Horário final" type="time" value={presence.end_time} onChange={v => setPresence({ ...presence, end_time: v })}/></div><SelectStand exhibitors={exhibitors} item={presence} setItem={setPresence}/><label className="text-xs font-bold">Observação<textarea value={presence.notes} onChange={e => setPresence({ ...presence, notes: e.target.value })} className="auth-input mt-1 h-20 w-full rounded-xl border p-3 text-sm"/></label><label className="flex gap-2 text-xs font-bold"><input type="checkbox" checked={presence.guaranteed} onChange={e => setPresence({ ...presence, guaranteed: e.target.checked })}/>Este horário está garantido.</label></>}
    {activeKind === 'book' && <><p className="text-xs font-bold text-[#8a3a63]">{bookItems.length}/3 livros para enviar</p>{bookItems.map((book, index) => <fieldset key={index} className="grid gap-3 rounded-2xl border border-[#edcddd] p-4"><legend className="px-1 text-sm font-black">Livro {index + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><Input label="Título" required value={book.title} onChange={v => setBookItems(items => items.map((x, i) => i === index ? { ...x, title: v } : x))}/><Input label="Editora" value={book.publisher} onChange={v => setBookItems(items => items.map((x, i) => i === index ? { ...x, publisher: v } : x))}/></div><Input label="Imagem da capa (URL)" type="url" value={book.cover_url} onChange={v => setBookItems(items => items.map((x, i) => i === index ? { ...x, cover_url: v } : x))} placeholder="https://…"/><Input label="Gênero" value={book.genre} onChange={v => setBookItems(items => items.map((x, i) => i === index ? { ...x, genre: v } : x))} placeholder="Ex.: romance sáfico"/><Input label="Tags separadas por vírgula" value={book.tags} onChange={v => setBookItems(items => items.map((x, i) => i === index ? { ...x, tags: v } : x))}/><label className="text-xs font-bold">Sinopse<textarea value={book.synopsis} onChange={e => setBookItems(items => items.map((x, i) => i === index ? { ...x, synopsis: e.target.value } : x))} className="auth-input mt-1 h-24 w-full rounded-xl border p-3 text-sm"/></label><div className="flex flex-wrap gap-4 text-xs font-bold"><label className="flex gap-2"><input type="checkbox" checked={book.autograph_available} onChange={e => setBookItems(items => items.map((x, i) => i === index ? { ...x, autograph_available: e.target.checked } : x))}/>Disponível para autógrafo</label><label className="flex gap-2"><input type="checkbox" checked={book.available_for_sale} onChange={e => setBookItems(items => items.map((x, i) => i === index ? { ...x, available_for_sale: e.target.checked } : x))}/>À venda na Bienal</label></div>{book.available_for_sale && <SelectStand exhibitors={exhibitors} item={book} setItem={next => setBookItems(items => items.map((x, i) => i === index ? next : x))}/>}<label className="flex gap-2 text-xs font-bold"><input type="checkbox" checked={book.featured} onChange={e => setBookItems(items => items.map((x, i) => i === index ? { ...x, featured: e.target.checked } : x))}/>Destacar no Passaporte</label>{bookItems.length > 1 && <button type="button" onClick={() => setBookItems(items => items.filter((_, i) => i !== index))} className="flex w-fit items-center gap-1 text-xs font-bold text-rose-600"><Trash2 size={14}/>Remover livro</button>}</fieldset>)}{bookItems.length < 3 && <button type="button" onClick={() => setBookItems(items => [...items, newBook()])} className="flex w-fit items-center gap-1 text-sm font-black text-[#a93773]"><Plus size={16}/>Adicionar outro livro</button>}</>}
    {activeKind === 'autograph' && <><div className="grid gap-3 md:grid-cols-3"><Input label="Data" type="date" required min={EVENT_START} max={EVENT_END} value={autograph.event_date} onChange={v => setAutograph({ ...autograph, event_date: v })}/><Input label="Horário inicial" type="time" required value={autograph.start_time} onChange={v => setAutograph({ ...autograph, start_time: v })}/><Input label="Horário final" type="time" value={autograph.end_time} onChange={v => setAutograph({ ...autograph, end_time: v })}/></div><SelectStand exhibitors={exhibitors} item={autograph} setItem={setAutograph}/><Input label="Livros (separados por vírgula)" value={autograph.books} onChange={v => setAutograph({ ...autograph, books: v })}/><label className="text-xs font-bold">Observações<textarea value={autograph.notes} onChange={e => setAutograph({ ...autograph, notes: e.target.value })} className="auth-input mt-1 h-20 w-full rounded-xl border p-3 text-sm"/></label></>}
    <button disabled={saving} className="route-primary-button mt-1 flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-black disabled:opacity-50"><Send className="h-4 w-4"/>{saving ? 'Enviando…' : 'Enviar para revisão'}</button></form><div className="mt-5 border-t pt-4"><h3 className="text-xs font-black uppercase tracking-wide">Solicitações enviadas</h3>{requests.slice(0, 5).map(request => <div key={request.id} className="mt-2 flex items-center justify-between rounded-xl bg-black/5 p-3 text-xs"><strong>{labels[request.request_type] || 'Informação enviada'}</strong><span>{statuses[request.status] || request.status}</span></div>)}</div></section>
}
