import React from 'react'
import { BookOpen, CalendarDays, MapPin, X } from 'lucide-react'
import { PassportPaper, PassportSeal, PassportTicket } from './PassportArt'

export default function AuthorPassportPreview({ author, profile, photoUrl, events = [], onClose }) {
  const agenda = events.filter(item => item.status !== 'rejected').slice(0, 4)
  return <div className="author-passport-preview fixed inset-0 z-[80] overflow-y-auto bg-[#160d1d]/90 p-3 sm:p-8">
    <div className="mx-auto max-w-[1180px]"><div className="mb-3 flex items-center justify-between gap-3 text-white"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#efb9d9]">Visualização da autora</p><h2 className="text-lg font-black">Como sua página final aparecerá</h2></div><button onClick={onClose} className="rounded-xl border border-white/40 px-3 py-2 text-sm font-bold"><X className="inline h-4 w-4"/> Fechar</button></div>
      <div className="passport-book">
        <PassportPaper className="passport-desktop-visible passport-mobile-active"><div className="passport-page-content"><div className="flex items-start justify-between gap-3"><PassportTicket className="passport-ticket"/><PassportSeal className="passport-seal"/></div><h3 className="passport-script passport-title mt-3 text-center">{author?.name}</h3><p className="mt-3 text-center text-sm">Autora sáfica <span className="mx-2 text-[#bd62a8]">•</span> Bienal do Livro 2026</p><div className="passport-profile-grid mt-7"><div>{photoUrl ? <img src={photoUrl} alt={author?.name} className="passport-photo"/> : <div className="passport-photo-placeholder">{author?.name?.[0] || 'A'}</div>}</div><div><div className="passport-note"><p className="passport-kicker flex items-center gap-2"><BookOpen className="h-5 w-5"/>Sobre a autora</p><p className="mt-3 whitespace-pre-line text-sm leading-6">{profile.bio || 'Sua bio aparecerá aqui quando for preenchida.'}</p></div><div className="mt-5"><p className="passport-kicker">Mensagem para você</p><p className="passport-script mt-3 text-lg leading-7">{profile.message || 'Sua mensagem para as leitoras aparecerá aqui.'}</p></div></div></div><div className="mt-7"><p className="passport-kicker flex items-center gap-2"><BookOpen className="h-5 w-5"/>Livros em destaque</p><p className="mt-3 text-sm text-[#795769]">Os livros aprovados e vinculados ao seu perfil aparecerão nesta seção.</p></div></div></PassportPaper>
        <PassportPaper className="passport-desktop-visible passport-mobile-active"><div className="passport-page-content"><div className="flex items-start justify-between"><div><p className="passport-kicker flex items-center gap-2"><MapPin className="h-5 w-5"/>Onde encontrar a autora</p><h3 className="passport-title mt-3 text-3xl">Agenda na Bienal</h3><p className="mt-3 text-sm">Presenças e sessões aprovadas pela equipe.</p></div><PassportSeal className="passport-seal"/></div><div className="passport-note mt-7 passport-agenda">{agenda.map((item, index) => <div key={item.id || index} className="passport-agenda-item"><div><p className="font-black"><CalendarDays className="mr-2 inline h-4 w-4"/>{item.payload?.event_date || item.payload?.presence_date || item.date || 'Data a confirmar'}</p><p className="mt-3 text-base">{item.payload?.start_time || item.start_time || 'Horário a confirmar'}</p></div><div><span className={`passport-badge ${item.request_type === 'presence' ? 'passport-badge--presence' : 'passport-badge--autograph'}`}>{item.request_type === 'presence' ? 'Presença confirmada' : 'Sessão de autógrafos'}</span><p className="mt-3"><span className="passport-stand">Estande {item.payload?.stand_code || item.stand_code || 'a confirmar'}</span></p></div></div>)}{!agenda.length && <p className="p-4 text-center text-sm">Sua agenda aprovada aparecerá aqui. Você ainda não tem eventos vinculados.</p>}</div><div className="passport-note mt-6"><p className="passport-kicker">Atualizações de última hora</p><p className="mt-3 text-sm">Informações aprovadas poderão ser incluídas nesta área até o evento.</p></div></div></PassportPaper>
      </div></div>
  </div>
}
